<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CoreRentalNet.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Modules/Catalog/CoreRentalNet.Modules.Catalog.Domain/CoreRentalNet.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="../../src/Modules/Catalog/CoreRentalNet.Modules.Catalog.Application/CoreRentalNet.Modules.Catalog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Modules/Catalog/CoreRentalNet.Modules.Catalog.Infrastructure/CoreRentalNet.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Modules/Workspace/CoreRentalNet.Modules.Workspace.Domain/CoreRentalNet.Modules.Workspace.Domain.csproj" />
    <ProjectReference Include="../../src/Modules/Workspace/CoreRentalNet.Modules.Workspace.Application/CoreRentalNet.Modules.Workspace.Application.csproj" />
    <ProjectReference Include="../../src/Modules/Workspace/CoreRentalNet.Modules.Workspace.Infrastructure/CoreRentalNet.Modules.Workspace.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Modules/Rentals/CoreRentalNet.Modules.Rentals.Domain/CoreRentalNet.Modules.Rentals.Domain.csproj" />
    <ProjectReference Include="../../src/Modules/Rentals/CoreRentalNet.Modules.Rentals.Application/CoreRentalNet.Modules.Rentals.Application.csproj" />
    <ProjectReference Include="../../src/Modules/Rentals/CoreRentalNet.Modules.Rentals.Infrastructure/CoreRentalNet.Modules.Rentals.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Modules/Discovery/CoreRentalNet.Modules.Discovery.Domain/CoreRentalNet.Modules.Discovery.Domain.csproj" />
    <ProjectReference Include="../../src/Modules/Discovery/CoreRentalNet.Modules.Discovery.Application/CoreRentalNet.Modules.Discovery.Application.csproj" />
    <ProjectReference Include="../../src/Modules/Discovery/CoreRentalNet.Modules.Discovery.Infrastructure/CoreRentalNet.Modules.Discovery.Infrastructure.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
