// <auto-generated />
using System;
using CoreRentalNet.Modules.Workspace.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreRentalNet.Modules.Workspace.Infrastructure.Migrations
{
    [DbContext(typeof(WorkspaceContext))]
    [Migration("20260910115826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CoreRentalNet.Modules.Workspace.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraftTokenHash")
                        .IsUnique();

                    b.ToTable("Workspace_Draft", (string)null);
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Workspace.Domain.Workspace", b =>
                {
                    b.OwnsMany("CoreRentalNet.Modules.Workspace.Domain.SlotAssignment", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("DraftId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Slot")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.HasKey("DraftId", "Slot");

                            b1.ToTable("Workspace_SlotAssignment", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DraftId");
                        });

                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
