// <auto-generated />
using System;
using CoreRentalNet.Modules.Rentals.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreRentalNet.Modules.Rentals.Infrastructure.Migrations
{
    [DbContext(typeof(RentalsContext))]
    [Migration("20260910121157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CoreRentalNet.Modules.Rentals.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("RentalId", "PeriodIndex")
                        .IsUnique();

                    b.ToTable("Rentals_Invoice", (string)null);
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Rentals.Domain.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ActivatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CancellationRequestedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DeliveryScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PlacedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Rentals_Rental", (string)null);
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Rentals.Infrastructure.NumberSequenceEntry", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Kind", "Year");

                    b.ToTable("Rentals_NumberSequence", (string)null);
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Rentals.Domain.Invoice", b =>
                {
                    b.OwnsMany("CoreRentalNet.Modules.Rentals.Domain.InvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Sku")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("LineTotal")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("UnitMonthlyPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.HasKey("InvoiceId", "Sku");

                            b1.ToTable("Rentals_InvoiceLine", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Rentals.Domain.Rental", b =>
                {
                    b.OwnsMany("CoreRentalNet.Modules.Rentals.Domain.RentalLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("RentalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Sku")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("UnitMonthlyPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.HasKey("RentalId", "Sku");

                            b1.ToTable("Rentals_RentalLine", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
