// <auto-generated />
using System;
using CoreRentalNet.Modules.Discovery.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreRentalNet.Modules.Discovery.Infrastructure.Migrations
{
    [DbContext(typeof(DiscoveryContext))]
    [Migration("20260920011951_SelectionSignal")]
    partial class SelectionSignal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CoreRentalNet.Modules.Discovery.Infrastructure.CatalogIndex", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogueHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Discovery_Index", (string)null);
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Discovery.Infrastructure.CatalogVector", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Sku");

                    b.ToTable("Discovery_CatalogVector", (string)null);
                });

            modelBuilder.Entity("CoreRentalNet.Modules.Discovery.Infrastructure.Selection.CatalogSelection", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("DecayedChosen")
                        .HasColumnType("REAL");

                    b.Property<double>("DecayedOffered")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Sku");

                    b.ToTable("Discovery_Selection", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
