<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CoreRentalNet.Modules.Workspace.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/CoreRentalNet.BuildingBlocks.Domain/CoreRentalNet.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
