using System.Text.Json;
using CoreRentalNet.BuildingBlocks.Infrastructure.Vectors;

namespace CoreRentalNet.IntegrationTests;

/// <summary>
/// The committed golden vectors the semantic-search tests run on.
/// </summary>
/// <remarks>
/// <para>
/// <b>The vectors are real model output, pinned so the suite can stay offline.</b> "Does a paraphrase find the
/// right product" cannot be answered with hand-written floats — <c>StandInEmbeddingService</c> says as much —
/// so they were produced once by <c>all-MiniLM-L6-v2-embedding</c> over the products' rendered text, exactly as
/// the ingestion tool renders it, and committed. The suite is deterministic and hermetic; what it gives up is
/// regeneration without a model.
/// </para>
/// <para>
/// <b>What is inside is data, not behaviour.</b> A query's vector is served by <see cref="FixtureEmbeddingService"/>
/// so the handler embeds without a server, and a product's vector is loaded into a temp <c>vec0</c> file so the
/// real <c>MATCH</c> ranks it. The fixture is regenerated by
/// <c>regenerate-catalog-embedding-fixture.py</c>.
/// </para>
/// </remarks>
internal sealed record CatalogEmbeddingFixture(
    CatalogEmbeddingFixtureRecipe Recipe,
    IReadOnlyList<CatalogEmbeddingFixtureProduct> Products,
    IReadOnlyList<CatalogEmbeddingFixtureQuery> Queries,
    IReadOnlyList<CatalogEmbeddingFixturePhrase> Characterisation)
{
    /// <summary>The fixture as committed, next to these tests.</summary>
    public static CatalogEmbeddingFixture Load()
    {
        var json = File.ReadAllText(
            RepoRoot.Combine("tests", "CoreRentalNet.IntegrationTests", "CatalogEmbeddingFixture.json"));

        return JsonSerializer.Deserialize<CatalogEmbeddingFixture>(
            json,
            new JsonSerializerOptions(JsonSerializerDefaults.Web))
            ?? throw new InvalidOperationException("CatalogEmbeddingFixture.json could not be read.");
    }

    /// <summary>The one query a test asks for by kind.</summary>
    public CatalogEmbeddingFixtureQuery Query(string kind)
        => Queries.Single(query => string.Equals(query.Kind, kind, StringComparison.Ordinal));

    public static float[] Floats(byte[] vector) => VectorBlob.ToFloats(vector);
}
